export const SDG_GOALS = [
    { id: 1, name: 'No Poverty', color: 'bg-red-600', textColor: 'text-red-600' },
    { id: 2, name: 'Zero Hunger', color: 'bg-amber-500', textColor: 'text-amber-500' },
    { id: 3, name: 'Good Health and Well-being', color: 'bg-green-600', textColor: 'text-green-600' },
    { id: 4, name: 'Quality Education', color: 'bg-red-700', textColor: 'text-red-700' },
    { id: 5, name: 'Gender Equality', color: 'bg-orange-600', textColor: 'text-orange-600' },
    { id: 6, name: 'Clean Water and Sanitation', color: 'bg-cyan-500', textColor: 'text-cyan-500' },
    { id: 7, name: 'Affordable and Clean Energy', color: 'bg-yellow-500', textColor: 'text-yellow-500' },
    { id: 8, name: 'Decent Work and Economic Growth', color: 'bg-rose-700', textColor: 'text-rose-700' },
    { id: 9, name: 'Industry, Innovation and Infrastructure', color: 'bg-orange-500', textColor: 'text-orange-500' },
    { id: 10, name: 'Reduced Inequalities', color: 'bg-pink-600', textColor: 'text-pink-600' },
    { id: 11, name: 'Sustainable Cities and Communities', color: 'bg-amber-600', textColor: 'text-amber-600' },
    { id: 12, name: 'Responsible Consumption and Production', color: 'bg-yellow-600', textColor: 'text-yellow-600' },
    { id: 13, name: 'Climate Action', color: 'bg-green-700', textColor: 'text-green-700' },
    { id: 14, name: 'Life Below Water', color: 'bg-blue-500', textColor: 'text-blue-500' },
    { id: 15, name: 'Life on Land', color: 'bg-lime-600', textColor: 'text-lime-600' },
    { id: 16, name: 'Peace, Justice and Strong Institutions', color: 'bg-blue-700', textColor: 'text-blue-700' },
    { id: 17, name: 'Partnerships for the Goals', color: 'bg-indigo-700', textColor: 'text-indigo-700' },
];